app:
  image: vfarcic/books-fe-polymer-dev
  volumes:
    - node_modules:/node_modules
    - bower_components:/bower_components
    - app:/app
  ports:
    - 8081:3000
nginxDev:
  image: nginx
  volumes:
    - conf/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - 8080:80
booksServiceDev:
  image: vfarcic/books-service
  volumes:
    - db:/data/db
  ports:
      - 8082:8080